version: '3'

services: 

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - task1-network
        depends_on:
            - laravel

    laravel:
        build: .docker/laravel
        container_name: laravel
        # entrypoint: dockerize -template ./.docker/laravel/.env:.env -wait tcp://mysql:3306 -timeout 40s ./.docker/laravel/entrypoint.sh
        # environment:
        #     - DB_HOST=mysql
        #     - DB_DATABASE=laravel
        #     - DB_USERNAME=root
        #     - DB_PASSWORD=root
        volumes: 
            - .:/var/www
        networks: 
            - task1-network
        depends_on: 
            - mysql
            - redis

    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks: 
            - task1-network

    mysql:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        tty: true
        ports: 
            - 33006:3306
        volumes: 
            - ./.docker/mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - task1-network
            
networks: 
    task1-network:
        driver: bridge
